users:
- name: ben.gallagher
  groups: sudo
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
  - cat "/Users/ben.gallagher/.ssh/id_ed25519.pub"
runcmd:
  - sudo apt update
  - sudo apt upgrade -y
  - curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable traefik" sh -
